# Configuration Doc:
# https://alacritty.org/config-alacritty.html

[window]
opacity = 0.85
#decorations = "none"

[window.padding]
x = 18
y = 16

[font]
size = 11

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[selection]
save_to_clipboard = true
